---
output: html_document
---
pKa analysis for XLOTX
========================================================
MF batch:  XBATCHX

## pKa
```{r Munge,echo=FALSE,dev='CairoPNG',warning=FALSE,message=FALSE,results='hide'}
library(knitr)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(ggthemes)
data<-read.csv('data.csv')
models<-lapply(split(data,data$dye),function(x){nls(counts ~ SSfpl(pH, Bottom, Top, pKa, Slope), x)})
pHvals <- seq(min(data$pH), max(data$pH), length.out=150) 
linedata<-lapply(models,function(u){predict(u, data.frame(pH=pHvals))[1:150]})
ld<-split(names(linedata),names(linedata))
titrlines<-lapply(ld,function(u){data.frame(val=linedata[[u]],dye=u,pH=pHvals)}) %>% Reduce(f='rbind')

titrPlot<-ggplot(data,aes(x=pH,y=counts))+geom_jitter(aes(fill=dye),colour=I(rgb(0,0,0,.4)),size=2,width=.1,shape=21) +geom_line(data=titrlines,aes(x=pH,y=val,colour=dye))+theme_few()+ggtitle('Titration Curve')+guides(colour = FALSE,fill=FALSE)


## lines for effective range
min10<-function(z){min(z) + ((max(z) - min(z))/10)}
max10<-function(z){max(z) - ((max(z) - min(z))/10)}
LowLine<-function(u){b<-min10(u);which(abs(u - b) == min(abs(u - b)))}
HighLine<-function(u){b<-max10(u);which(abs(u - b) == min(abs(u - b)))}
#
pH.index<-c(lapply(linedata,LowLine),lapply(linedata,HighLine))%>%Reduce(f='rbind')

EfRange<-data.frame(vline=pHvals[pH.index],dye=factor(c('CL','PR')))

gainData<-lapply(models,function(u){predict(u, data.frame(pH=pHvals))[1:150]}) %>%
(function(u){split(names(u),names(u))}) %>%
lapply(function(x){data.frame(gain=diff(linedata[[x]][1:150])/diff(pHvals)/1000,pH=pHvals[-1],dye=x)}) %>% Reduce(f='rbind') %>% mutate(dye=factor(dye))


gain_plot<-ggplot(gainData,aes(x=pH,y=gain,colour=dye)) + geom_line(width=4) +theme_few() +ggtitle('Gain Curve') + geom_vline(data=EfRange,aes(xintercept=vline,colour=dye),linetype = 'dotted')
```
```{r plots,echo=FALSE,warning=FALSE,message=FALSE,fig.width=14,fig.height=6,dev='CairoPNG',fig.cap=''}
grid.arrange(titrPlot,gain_plot, nrow=1, ncol=2,top='pKA')
```  

## Effective range  
```{r Effective range,echo=FALSE,warning=FALSE,message=FALSE}
EfRange$stat<-c(rep('Low.pH',2),rep('High.pH',2))
fix<-c('CL'='Clear','PR'='Phenol Red')
EfRange$dye<-fix[EfRange$dye]
```
`r kable(t(xtabs(vline~.,data=EfRange)),format='markdown')`

## Clear pKa information
```{r Clear pKa information,echo=FALSE,warning=FALSE,message=FALSE}
Clear.V50<-cbind(signif(summary(models[['CL']])$parameters,digits=5),
signif(confint(models[['CL']]),digits=4))
```
`r kable(Clear.V50,format='markdown')`

## Phenol Red pKa information
```{r Phenol Red pKa information,echo=FALSE,warning=FALSE,message=FALSE}
Phenol.Red.V50<-cbind(signif(summary(models[['PR']])$parameters,digits=5),
signif(confint(models[['PR']]),digits=4))
```
`r kable(Phenol.Red.V50,format='markdown')`

